routes/web.php
//Route::post('admin/login', 'Admin\Auth\LoginController@login');
//Route::get('admin/logout', 'Admin\Auth\LoginController@logout');



Route::get('/dashboard', 'Admin\DashboardController@index')->name('home');

Route::get('issued_tickets/genbarcodeofticket/{id}', 'Admin\IssuedTicketController@genbarcodeofticket')->name('admin.issued_tickets.genbarcodeofticket');

// Route::group(['prefix' => 'admin','as' => 'admin.','namespace' => 'Admin', 'middleware' => []], function () {
//     Route::get('issued_tickets/genbarcodeofticket/{id}', 'IssuedTicketController@genbarcodeofticket')->name('issued_tickets.genbarcodeofticket');

// });

Route::group(['prefix' => 'admin','as' => 'admin.','namespace' => 'Admin', 'middleware' => ['auth','check_permissions']], function () {

    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/', 'DashboardController@index');
    // Additional routes for users
	Route::post('users/bulkshow', ['as'=>'users.bulkshow','uses'=>'UsersController@bulkshow']);
    Route::post('users/bulkhide', ['as'=>'users.bulkhide','uses'=>'UsersController@bulkhide']);
    Route::post('users/bulkdelete', ['as'=>'users.bulkdelete','uses'=>'UsersController@bulkdelete']);
    Route::post('users/datatable', ['as'=>'users.datatable','uses'=>'UsersController@datatable']);

	// Additional routes for roles
    Route::post('roles/bulkshow',  ['as'=>'roles.bulkshow','uses'=>'RoleController@bulkshow']);
    Route::post('roles/bulkhide',  ['as'=>'roles.bulkhide','uses'=>'RoleController@bulkhide']);
    Route::post('roles/bulkdelete', ['as'=>'roles.bulkdelete','uses'=>'RoleController@bulkdelete']);
    Route::post('roles/datatable',  ['as'=>'roles.datatable','uses'=>'RoleController@datatable']);

    // Additional routes for events
    Route::match(['GET', 'PUT'], "events/{event_id}/addeditevent", ['as' => 'events.addeditevent', 'uses' => 'EventController@addeditevent']);
    Route::post('events/bulkshow',  ['as'=>'events.bulkshow','uses'=>'EventController@bulkshow']);
    Route::post('events/bulkhide',  ['as'=>'events.bulkhide','uses'=>'EventController@bulkhide']);
    Route::post('events/bulkdelete', ['as'=>'events.bulkdelete','uses'=>'EventController@bulkdelete']);
    Route::post('events/datatable',  ['as'=>'events.datatable','uses'=>'EventController@datatable']);
    Route::post('events/{event_id}/status',  ['as'=>'events.status','uses'=>'EventController@status']);
    Route::post('events/{event_id}/selling',  ['as'=>'events.selling','uses'=>'EventController@selling']);
    Route::post('events/checkIfEventHasRunningTicket', 'EventController@checkIfEventHasRunningTicket');
    Route::post('events/checkIfEventHasRequestOrTicket', 'EventController@checkIfEventHasRequestOrTicket');
    Route::post('events/checkIfTierHasRequestOrTicket', 'EventController@checkIfTierHasRequestOrTicket');

    // Additional routes for Documents
    Route::post('documents/bulkshow', 'DocumentController@bulkshow');
    Route::post('documents/bulkhide', 'DocumentController@bulkhide');
    Route::post('documents/bulkdelete', 'DocumentController@bulkdelete');
    Route::post('documents/datatable', 'DocumentController@datatable');


    ////////// by iqbal ////////////////////

    // Additional routes for events
   // Route::match(['GET', 'PUT'], "event_requests/{event_request_id}/addediteventrequest", ['as' => 'event_requests.addediteventrequest', 'uses' => 'EventRequestController@addediteventrequest']);
   // Route::post('event_requests/bulkshow',  ['as'=>'events.bulkshow','uses'=>'EventRequestController@bulkshow']);
   // Route::post('event_requests/bulkhide',  ['as'=>'events.bulkhide','uses'=>'EventRequestController@bulkhide']);

    Route::post('event_requests/bulkreject', ['as'=>'event_requests.bulkreject','uses'=>'EventRequestController@bulkreject']);
    Route::post('event_requests/bulkdelete', ['as'=>'event_requests.bulkdelete','uses'=>'EventRequestController@bulkdelete']);

    Route::post('event_requests/datatable',  ['as'=>'events.datatable','uses'=>'EventRequestController@datatable']);

    Route::post('event_requests/getreasonbytype', 'EventRequestController@getreasonbytype');
    Route::post('event_requests/getdescriptionbyreason', 'EventRequestController@getdescriptionbyreason');




    Route::post('event_requests/{event_request_id}/pending_status',  ['as'=>'event_requests.pending_status','uses'=>'EventRequestController@pending_status']);




    Route::post('event_requests/{event_request_id}/issue_status',  ['as'=>'event_requests.issue_status','uses'=>'EventRequestController@issue_status']);
    Route::post('event_requests/{event_request_id}/reject_status',  ['as'=>'event_requests.reject_status','uses'=>'EventRequestController@reject_status']);
    Route::post('event_requests/{event_request_id}/selling',  ['as'=>'event_requests.selling','uses'=>'EventRequestController@selling']);


    Route::post('issued_tickets/bulkreject', ['as'=>'issued_tickets.bulkreject','uses'=>'IssuedTicketController@bulkreject']);
    Route::post('issued_tickets/getreasonbytype', 'IssuedTicketController@getreasonbytype');
    Route::post('issued_tickets/getdescriptionbyreason', 'IssuedTicketController@getdescriptionbyreason');
    Route::post('issued_tickets/datatable',  ['as'=>'events.datatable','uses'=>'IssuedTicketController@datatable']);

    Route::post('issued_tickets/bulkissuedticketsdelete',  ['as'=>'events.bulkissuedticketsdelete','uses'=>'IssuedTicketController@bulkdelete']);
    //////////// end by iqbal //////////////






    //Additional routes for additional images
    Route::post('additionalimages/datatable', ['as'=>'additionalimages.datatable','uses'=>'AdditionalImageController@datatable']);
    Route::post('additionalimages/uploadimage', ['as'=>'additionalimages.uploadimage','uses'=>'AdditionalImageController@uploadimage']);
    Route::post('additionalimages/delimage', ['as'=>'additionalimages.delimage','uses'=>'AdditionalImageController@delimage']);
    Route::post('additionalimages/editcaption', ['as'=>'additionalimages.editcaption','uses'=>'AdditionalImageController@editcaption']);
    Route::post('additionalimages/bulkimagedelete',['as'=>'additionalimages.bulkimagedelete','uses'=>'AdditionalImageController@bulkimagedelete']);
    Route::post('additionalimages/reorder', ['as'=>'additionalimages.reorder','uses'=>'AdditionalImageController@reorder']);

    //Additional routes for tiers

    Route::post('tiers/datatable', ['as'=>'tiers.datatable','uses'=>'TierController@datatable']);
    Route::post('tiers/addtier', ['as'=>'tiers.addtier','uses'=>'TierController@addtier']);
    Route::post('tiers/deltier', ['as'=>'tiers.deltier','uses'=>'TierController@deltier']);
    Route::post('tiers/edittier', ['as'=>'tiers.edittier','uses'=>'TierController@edittier']);
    Route::post('tiers/bulkdelete',['as'=>'tiers.bulkdelete','uses'=>'TierController@bulkdelete']);
    Route::post('tiers/reorder', ['as'=>'tiers.reorder','uses'=>'TierController@reorder']);


    // Additional routes for reasons
    Route::post('reasons/bulkshow',  ['as'=>'reasons.bulkshow','uses'=>'ReasonController@bulkshow']);
    Route::post('reasons/bulkhide',  ['as'=>'reasons.bulkhide','uses'=>'ReasonController@bulkhide']);
    Route::post('reasons/bulkdelete', ['as'=>'reasons.bulkdelete','uses'=>'ReasonController@bulkdelete']);
    Route::post('reasons/datatable',  ['as'=>'reasons.datatable','uses'=>'ReasonController@datatable']);

    // resource routes
    Route::resource('tiers', 'TierController');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UsersController');
    Route::resource('events', 'EventController');
    Route::resource('settings', 'SettingController');
    Route::resource('documents', 'DocumentController');

    //by iqbal
   // Route::get('event_requests/viewtickets/{event_id}', 'EventRequestController@viewtickets')->name('event_requests.viewtickets');
    Route::get('event_requests/{event_id}', 'EventRequestController@index')->name('event_requests');
    Route::resource('event_requests', 'EventRequestController');

    Route::post('issued_tickets/datatableCancelledTicket',  ['as'=>'events.datatable','uses'=>'IssuedTicketController@datatableCancelledTicket']);

    Route::post('issued_tickets/{issued_ticket_id}/cancelled_status',  ['as'=>'issued_tickets.cancelled_status','uses'=>'IssuedTicketController@cancelled_status']);
    Route::post('issued_tickets/{issued_ticket_id}/refunded_status',  ['as'=>'issued_tickets.refunded_status','uses'=>'IssuedTicketController@refunded_status']);
    Route::post('issued_tickets/{issued_ticket_id}/reject_status',  ['as'=>'issued_tickets.reject_status','uses'=>'IssuedTicketController@reject_status']);
//   Route::get('issued_tickets/genbarcodeofticket/{id}', 'IssuedTicketController@genbarcodeofticket')->name('issued_tickets.genbarcodeofticket');
    Route::get('issued_tickets/viewissuedticket/{id}', 'IssuedTicketController@viewissuedticket')->name('issued_tickets.viewissuedticket');
    Route::get('issued_tickets/resend_ticket/{id}', 'IssuedTicketController@resend_ticket')->name('issued_tickets.resend_ticket');
    Route::get('issued_tickets/cancelledticket/{id}', 'IssuedTicketController@cancelledticket')->name('issued_tickets.cancelledticket');
    Route::post('issued_tickets/store/{id}', 'IssuedTicketController@store')->name('issued_tickets.store');
    Route::get('issued_tickets/create/{id}', 'IssuedTicketController@create')->name('issued_tickets.create');
    Route::get('issued_tickets/{id}', 'IssuedTicketController@index')->name('issued_tickets');
    Route::resource('issued_tickets', 'IssuedTicketController', ['except' => ['create', 'store', 'update']]);

    // end by iqblal
    Route::resource('reasons', 'ReasonController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('additionalimages', 'AdditionalImageController');
   // Auth::routes();
});

app/Models/Event_request.php
<?php

namespace Ticketing\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Event_request extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
    public static $status_YN = [1 =>'Public',2 =>'Admin'];

//    protected $fillable = [
//        'customer_id',
//        'event_id',
//        'total_qty',
//        'total_price',
//        'pre_request_no',
//        'post_request_no',
//        'complete_request_no',
//        'event_request_status_id',
//        'request_from',
//        'setting_id',
//        'last_edit_by',
//        'status',
//        'deleted_at',
//
//    ];








    public function event_request_details()
    {
        return $this->hasMany('Ticketing\Models\Event_request_detail');
    }


    public function event_request_status(){
        return $this->belongsTo('Ticketing\Models\Event_request_status');
    }

    public function customer(){
        return $this->belongsTo('Ticketing\Models\Customer');
    }

    public static function getTierColorByTierId($id){
        $tier=Tier::find($id);
        return $tier;
    }

    public static function boot()
    {
        parent::boot();

//        self::creating(function($object){
//            $object->event_id_str = Event::genRandomId();
//        });


        self::updating(function($object){

            if($object)
            {
                $changed = $object->isDirty() ? $object->getDirty() : false;
                $changed = empty($changed) ? false : $changed;

                if ($changed) {
                    $object->last_edit_by = Auth::user()->id;
                }
            }

        });





        Event_request::deleting(function($model)
        {
            foreach ($model->event_request_details as $event_request_detail)
            {
                $event_request_detail->delete();
            }

        });
    }


}

resources/views/admin/event_requests/_tiers_tiles.blade.php
<div class="row">
	<div class="col-md-10">
		<div class="event_listing_info" >
		    <div class="col-md-12 info-basic">
				<a style="color: black;font-size: 16px;font-weight: 700"  href="{{ route("admin.event_requests.edit",$event_request->id) }}"><span class="right-space">{{$twelve_digit_id}}</span></a> <span class="right-space">{{$created_at}}</span>
		    </div>
			<div class="col-md-12  info-basic">
				<span class="right-space">{{$customer_full_name}}</span>
			</div>
			<div class="col-md-12 info-basic">
				<span class="right-space">{{$customer_mobile}}</span> <span class="right-space">{{$customer_email}}</span>
			</div>

			<?php
			// echo 'pre>';
			// print_r($tiers);
             //  use App\Http\Helpers\Custom;
			?>

			@if(count($tiers)>0)
			@foreach (array_chunk($tiers,3) as $chunked_tiers)
				<div>
					@foreach ($chunked_tiers as $tier)

						{{--{{ $tier['tier_id']}}--}}
					   {{--{{'dddd'}}--}}
					{{--die;--}}

						<?php
					   $num=0;
                        $tl=$event_request->getTierColorByTierId($tier['tier_id']);



                       // $tl=\App\Http\Helpers\Custom::getTierColorByTierId($tier['tier_id']);
                       // print_r($tl);
						?>
						@if($tl)

						<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="margin-bottom: 5px">
							<div class="tier_tiles">
								<div style="margin-right:-18px;">
									<div class="col-sm-4 tile-stats-div" style="font-size: 20px; padding-top: 5px;  padding-left: 2px;
">
				                        <span class="tile-stats" >
				                            <span class="tile-margin-right" style="font-size: 16px;">R <strong> {{$tier['total_qty']}}</strong></span>
				                        </span>

									</div>
									<div class="col-sm-8 tile-border-left" style="background-color:#{{$tl->header_color}};color:white;
											height: 42px;margin-left: -18px;">
										<center>
											<span class="tile-title" style="display: block;direction: rtl;">{{$tl->title_arabic }}</span>
										</center>
									</div>
								</div>
							</div>
						</div>

						@endif
					@endforeach
					<br><br><br>
				</div>
			@endforeach
			@endif

		</div>
	</div>


</div>

resources/views/admin/event_requests/_viewtickets_tiers_tiles.blade.php
<div class="row">
	<div class="col-md-12">
		<div class="event_listing_info">
		    <div class="col-md-12 info-basic">
		         <span class="right-space">{{$twelve_digit_id}}</span> <span class="right-space">{{$created_at}}</span>
		    </div>
			<div class="col-md-12 info-basic">
				<span class="right-space">{{$customer_full_name}}</span>
			</div>
			<div class="col-md-12 info-basic">
				<span class="right-space">{{$customer_mobile}}</span> <span class="right-space">{{$customer_email}}</span>
			</div>

			@if(count($tiers)>0)
			@foreach (array_chunk($tiers,3) as $chunked_tiers)
				<div>
					@foreach ($chunked_tiers as $tier)

						{{--{{ $tier['tier_id']}}--}}
					   {{--{{'dddd'}}--}}
					{{--die;--}}

						<?php
					   $num=0;
                        $tl=$issued_ticket->getTierColorByTierId($tier['tier_id']);
                       // $tl=\App\Http\Helpers\Custom::getTierColorByTierId($tier['tier_id']);
                       // print_r($tl);
						?>

						<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
							<div class="tier_tiles">
								<div style="margin-right:-16px;">
									<div class="col-sm-5 tile-stats-div" style="font-size: 20px; padding-top: 5px">
				                        <span class="tile-stats" >
				                            <span class="tile-margin-right" style="font-size: 20px;">R <strong> {{$tier['total_qty']}}</strong></span>
				                        </span>

									</div>
									<div class="col-sm-6 tile-border-left" style="background-color:#{{$tl->header_color}};color:white;">
										<center>
											<span class="tile-title" style="display: block;direction: rtl;">{{$tl->title_arabic }}</span>
										</center>
									</div>
								</div>
							</div>
						</div>
					@endforeach
					<br><br><br>
				</div>
			@endforeach
			@endif
		</div>
	</div>
</div>

resources/views/admin/event_requests/create.blade.php
@include('admin.events.form',['event'=>$event,'tags'=>$tags,'request_type'=>$request_type])

resources/views/admin/event_requests/viewtickets.blade.php
@extends('layouts.app')
@section('content')
<style type="text/css">
    table#datatable-example4,table#datatable-example3,table#datatable-example2,table#datatable-example{
        width: 100% !important;
    }

    .nav-navbar-center {
        margin-top: 0px;
    }
</style>
<div class="page-title">
    <center>
        @if($event->eventStatusById($event->id))
            <span class="legends"><i class="fa fa-circle selling_on_icon legend_icon"></i><span class="legend_text" style="font-weight: bold">{{$event->event_id_str}}</span></span>
        @else
            <span class="legends"><i class="fa fa-circle-o selling_of_icon legend_icon"></i><span class="legend_text" style="font-weight: bold">{{$event->event_id_str}}</span></span>
        @endif
        <br/>
        <span style="font-weight: bold">{{$event->title_english}}</span>
        <br/>
        <span style="font-weight: bold">{{$event->title_arabic}}</span>
        <br/>
    </center>
</div>


<div class="page-title">
    <center>
        <h3>View Tickets جميع طلبات الحدث</h3>
        <br/>
        <span>Translate between 103 languages by typing</span>
        <br/>
        <span>ترجم بين 103 لغة عن طريق الكتابة</span>
        <br/>
    </center>
</div>


<br>


<div class='control' style="font-size: 18px">
    <div class="nav-navbar-center">
        <ul class="nav nav-pills">
            <li style="margin-right: 20px">Total Sold حضرها<br/><span style="font-size: 24px; color: #0078d7" >{{$issued_tiers_qty_sum}}</span> </li>
            <li style="margin-left: 20px">Total Available تم البيع<br/><span style="font-size: 24px; color: #6b6b6c" >{{$available_qty}}</span></li>
        </ul>
    </div>
</div>
<br>

<div class='control'>
    <div class="nav-navbar-center">
        <ul class="nav nav-pills">
            <li id="issued_tab"><a href="#issued_event_requests" data-toggle="tab">Issued ({{$issued_count}})</a></li>
            <li id="cancelled_tab"><a href="#cancelled_event_requests " data-toggle="tab">Cancelled ({{$cancelled_count}})</a></li>
        </ul>
    </div>
</div>

<br/>


<div class="tab-content">

    <div id="issued_event_requests" class="tab-pane fade">
        <div class="grid simple vertical green mobile-scroll">
            <div class="grid-title no-border"></div>
            <div class="grid-body no-border">
                <div class="pull-left markaction">
                    @if(Auth::user()->can("events-destroy"))
                        <a id="del" href="javascript:void(0)" class="btn btn-danger" data-url="{{ URL::to('admin/events/bulkdelete') }}">+ Issue exclusive tickets</a>
                    @endif
                </div>
                <div class="pull-right markaction">
                    @if(Auth::user()->can("events-destroy"))
                        <a id="del" href="javascript:void(0)" class="btn btn-danger" data-url="{{ URL::to('admin/events/bulkdelete') }}">Delete</a>
                    @endif
                </div>
                <br><br><br>
                <table class="table table-hover table-condensed" id="datatable-example" >
                    <thead>
                        <tr>
                            <th><input type="checkbox" class="group-checkable" data-set="#datatable-example .checkboxes" /></th>
                            <th>Id</th>
                            <th>عنوان <br> Information</th>
                            <th>شعار <br> Total(SR)</th>
                            <th>نشرت <br> Status</th>
                            <th>آخر تحديث <br> Last Edit</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <div id="cancelled_event_requests" class="tab-pane fade">
        <div class="grid simple vertical green mobile-scroll">
            <div class="grid-title no-border"></div>
            <div class="grid-body no-border">
                <div class="pull-right markaction">
                    @if(Auth::user()->can("events-destroy"))
                        <a id="del2" href="javascript:void(0)" class="btn btn-danger" data-url="{{ URL::to('admin/events/bulkdelete') }}">Delete</a>
                    @endif
                </div><br><br><br>

                <table class="table table-hover table-condensed" id="datatable-example2" >
                    <thead>
                        <tr>
                            <th><input type="checkbox" class="group-checkable" data-set="#datatable-example2 .checkboxes" /></th>
                            <th>Id</th>

                            <th>عنوان <br> Information</th>
                            <th>شعار <br> Total(SR)</th>
                            <th>نشرت <br> Status</th>
                            <th>آخر تحديث <br> Last Edit</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>


</div>
{!! Form::open(['method' => 'POST','class' => 'inline','id'=> 'bulkaction']) !!}
<input type="hidden" value="" name="ids" id="ids" />
{!! Form::close() !!}
@endsection

@section('page_script')
@parent
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function ($) {
        var event_type = '{{Request::get("source")}}';
        if(event_type == 'issued'){
            $( "#issued_tab" ).addClass( "active" );
            $( "#issued_event_requests" ).addClass( "active in" );
            $( "#cancelled_tab" ).removeClass( "active" );
        }else if(event_type == 'cancelled'){
            $( "#cancelled_tab" ).addClass( "active" );
            $( "#cancelled_event_requests" ).addClass( "active in" );
            $( "#issued_tab" ).removeClass( "active" );
        } else{
            $( "#issued_tab" ).addClass( "active" );
            $( "#issued_event_requests" ).addClass( "active in" );
            $( "#cancelled_tab" ).removeClass( "active" );
        }


        $('#issued_tab').click(function(event){
            history.pushState({}, null, "{{URL::route('admin.event_requests.viewtickets',$event->id)}}?source=issued");
        });
        $('#cancelled_tab').click(function(event){
            history.pushState({}, null, "{{URL::route('admin.event_requests.viewtickets',$event->id)}}?source=cancelled");
        });

        $('#datatable-example').DataTable({
            serverSide: false,
            'pageLength': 25,
            "order": [[1, "desc"]],
            ajax: {
                "url": "{{ URL::to('admin/event_requests/datatable1') }}",
                "type": "POST",
                "data": {
                    'eventid':'{{$eventid}}',
                    'type':3
                     }
            },
            columns: [
                {data: 'check', name: 'check'},
                {data: 'id', name: 'id'},
                {data: 'info', name: 'info'},
                {data: 'total_price', name: 'total_price'},
                {data: 'status', name: 'status'},
                {data: 'updated_by', name: 'updated_by'},
                {data: 'actions', name: 'actions'}
            ],
            "columnDefs": [
                {
                    "targets": [1],
                    "visible": false,
                    "searchable": false
                },
                {
                    "targets": [0,2,6],
                    "searchable": false
                },
                {
                    "targets": [0, 1, 2, 3, 4, 5, 6],
                    "orderable": false
                }
            ]
        });

        $('#datatable-example2').DataTable({
            serverSide: false,
            'pageLength': 25,
            "order": [[1, "desc"]],
            ajax: {
                "url": "{{ URL::to('admin/event_requests/datatable1') }}",
                "type": "POST",
                "data": {
                         'eventid':'{{$eventid}}',
                         'type':4
                    }
            },
            columns: [
                {data: 'check', name: 'check'},
                {data: 'id', name: 'id'},
                {data: 'info', name: 'info'},
                {data: 'total_price', name: 'total_price'},
                {data: 'status', name: 'status'},
                {data: 'updated_by', name: 'updated_by'},
                {data: 'actions', name: 'actions'}
            ],
            "columnDefs": [
                {
                    "targets": [1],
                    "visible": false,
                    "searchable": false
                },
                {
                    "targets": [0,2,6],
                    "searchable": false
                },
                {
                    "targets": [0, 1, 2, 3, 4, 5, 6],
                    "orderable": false
                }
            ]
        });
    });
</script>

@endsection