routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/admin', 'HomeController@index')->name('home');
//Route::get('/admin', function () {
////    return view('welcome');
//    return redirect('admin/');
//});
//Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm');
//Route::post('admin/login', 'Admin\Auth\LoginController@login');
//Route::get('admin/logout', 'Admin\Auth\LoginController@logout');



Route::get('/dashboard', 'Admin\DashboardController@index')->name('home');

Route::get('issued_tickets/genbarcodeofticket/{id}', 'Admin\IssuedTicketController@genbarcodeofticket')->name('admin.issued_tickets.genbarcodeofticket');

// Route::group(['prefix' => 'admin','as' => 'admin.','namespace' => 'Admin', 'middleware' => []], function () {
//     Route::get('issued_tickets/genbarcodeofticket/{id}', 'IssuedTicketController@genbarcodeofticket')->name('issued_tickets.genbarcodeofticket');

// });

Route::group(['prefix' => 'admin','as' => 'admin.','namespace' => 'Admin', 'middleware' => ['auth','check_permissions']], function () {

    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/', 'DashboardController@index');
    // Additional routes for users
	Route::post('users/bulkshow', ['as'=>'users.bulkshow','uses'=>'UsersController@bulkshow']);
    Route::post('users/bulkhide', ['as'=>'users.bulkhide','uses'=>'UsersController@bulkhide']);
    Route::post('users/bulkdelete', ['as'=>'users.bulkdelete','uses'=>'UsersController@bulkdelete']);
    Route::post('users/datatable', ['as'=>'users.datatable','uses'=>'UsersController@datatable']);

	// Additional routes for roles
    Route::post('roles/bulkshow',  ['as'=>'roles.bulkshow','uses'=>'RoleController@bulkshow']);
    Route::post('roles/bulkhide',  ['as'=>'roles.bulkhide','uses'=>'RoleController@bulkhide']);
    Route::post('roles/bulkdelete', ['as'=>'roles.bulkdelete','uses'=>'RoleController@bulkdelete']);
    Route::post('roles/datatable',  ['as'=>'roles.datatable','uses'=>'RoleController@datatable']);

    // Additional routes for events
    Route::match(['GET', 'PUT'], "events/{event_id}/addeditevent", ['as' => 'events.addeditevent', 'uses' => 'EventController@addeditevent']);
    Route::post('events/bulkshow',  ['as'=>'events.bulkshow','uses'=>'EventController@bulkshow']);
    Route::post('events/bulkhide',  ['as'=>'events.bulkhide','uses'=>'EventController@bulkhide']);
    Route::post('events/bulkdelete', ['as'=>'events.bulkdelete','uses'=>'EventController@bulkdelete']);
    Route::post('events/datatable',  ['as'=>'events.datatable','uses'=>'EventController@datatable']);
    Route::post('events/{event_id}/status',  ['as'=>'events.status','uses'=>'EventController@status']);
    Route::post('events/{event_id}/selling',  ['as'=>'events.selling','uses'=>'EventController@selling']);
    Route::post('events/checkIfEventHasRunningTicket', 'EventController@checkIfEventHasRunningTicket');
    Route::post('events/checkIfEventHasRequestOrTicket', 'EventController@checkIfEventHasRequestOrTicket');
    Route::post('events/checkIfTierHasRequestOrTicket', 'EventController@checkIfTierHasRequestOrTicket');

    // Additional routes for Documents
    Route::post('documents/bulkshow', 'DocumentController@bulkshow');
    Route::post('documents/bulkhide', 'DocumentController@bulkhide');
    Route::post('documents/bulkdelete', 'DocumentController@bulkdelete');
    Route::post('documents/datatable', 'DocumentController@datatable');


    ////////// by iqbal ////////////////////

    // Additional routes for events
   // Route::match(['GET', 'PUT'], "event_requests/{event_request_id}/addediteventrequest", ['as' => 'event_requests.addediteventrequest', 'uses' => 'EventRequestController@addediteventrequest']);
   // Route::post('event_requests/bulkshow',  ['as'=>'events.bulkshow','uses'=>'EventRequestController@bulkshow']);
   // Route::post('event_requests/bulkhide',  ['as'=>'events.bulkhide','uses'=>'EventRequestController@bulkhide']);

    Route::post('event_requests/bulkreject', ['as'=>'event_requests.bulkreject','uses'=>'EventRequestController@bulkreject']);
    Route::post('event_requests/bulkdelete', ['as'=>'event_requests.bulkdelete','uses'=>'EventRequestController@bulkdelete']);

    Route::post('event_requests/datatable',  ['as'=>'events.datatable','uses'=>'EventRequestController@datatable']);

    Route::post('event_requests/getreasonbytype', 'EventRequestController@getreasonbytype');
    Route::post('event_requests/getdescriptionbyreason', 'EventRequestController@getdescriptionbyreason');




    Route::post('event_requests/{event_request_id}/pending_status',  ['as'=>'event_requests.pending_status','uses'=>'EventRequestController@pending_status']);




    Route::post('event_requests/{event_request_id}/issue_status',  ['as'=>'event_requests.issue_status','uses'=>'EventRequestController@issue_status']);
    Route::post('event_requests/{event_request_id}/reject_status',  ['as'=>'event_requests.reject_status','uses'=>'EventRequestController@reject_status']);
    Route::post('event_requests/{event_request_id}/selling',  ['as'=>'event_requests.selling','uses'=>'EventRequestController@selling']);


    Route::post('issued_tickets/bulkreject', ['as'=>'issued_tickets.bulkreject','uses'=>'IssuedTicketController@bulkreject']);
    Route::post('issued_tickets/getreasonbytype', 'IssuedTicketController@getreasonbytype');
    Route::post('issued_tickets/getdescriptionbyreason', 'IssuedTicketController@getdescriptionbyreason');
    Route::post('issued_tickets/datatable',  ['as'=>'events.datatable','uses'=>'IssuedTicketController@datatable']);

    Route::post('issued_tickets/bulkissuedticketsdelete',  ['as'=>'events.bulkissuedticketsdelete','uses'=>'IssuedTicketController@bulkdelete']);
    //////////// end by iqbal //////////////






    //Additional routes for additional images
    Route::post('additionalimages/datatable', ['as'=>'additionalimages.datatable','uses'=>'AdditionalImageController@datatable']);
    Route::post('additionalimages/uploadimage', ['as'=>'additionalimages.uploadimage','uses'=>'AdditionalImageController@uploadimage']);
    Route::post('additionalimages/delimage', ['as'=>'additionalimages.delimage','uses'=>'AdditionalImageController@delimage']);
    Route::post('additionalimages/editcaption', ['as'=>'additionalimages.editcaption','uses'=>'AdditionalImageController@editcaption']);
    Route::post('additionalimages/bulkimagedelete',['as'=>'additionalimages.bulkimagedelete','uses'=>'AdditionalImageController@bulkimagedelete']);
    Route::post('additionalimages/reorder', ['as'=>'additionalimages.reorder','uses'=>'AdditionalImageController@reorder']);

    //Additional routes for tiers

    Route::post('tiers/datatable', ['as'=>'tiers.datatable','uses'=>'TierController@datatable']);
    Route::post('tiers/addtier', ['as'=>'tiers.addtier','uses'=>'TierController@addtier']);
    Route::post('tiers/deltier', ['as'=>'tiers.deltier','uses'=>'TierController@deltier']);
    Route::post('tiers/edittier', ['as'=>'tiers.edittier','uses'=>'TierController@edittier']);
    Route::post('tiers/bulkdelete',['as'=>'tiers.bulkdelete','uses'=>'TierController@bulkdelete']);
    Route::post('tiers/reorder', ['as'=>'tiers.reorder','uses'=>'TierController@reorder']);


    // Additional routes for reasons
    Route::post('reasons/bulkshow',  ['as'=>'reasons.bulkshow','uses'=>'ReasonController@bulkshow']);
    Route::post('reasons/bulkhide',  ['as'=>'reasons.bulkhide','uses'=>'ReasonController@bulkhide']);
    Route::post('reasons/bulkdelete', ['as'=>'reasons.bulkdelete','uses'=>'ReasonController@bulkdelete']);
    Route::post('reasons/datatable',  ['as'=>'reasons.datatable','uses'=>'ReasonController@datatable']);

    // resource routes
    Route::resource('tiers', 'TierController');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UsersController');
    Route::resource('events', 'EventController');
    Route::resource('settings', 'SettingController');
    Route::resource('documents', 'DocumentController');

    //by iqbal
   // Route::get('event_requests/viewtickets/{event_id}', 'EventRequestController@viewtickets')->name('event_requests.viewtickets');
    Route::get('event_requests/{event_id}', 'EventRequestController@index')->name('event_requests');
    Route::resource('event_requests', 'EventRequestController');

    Route::post('issued_tickets/datatableCancelledTicket',  ['as'=>'events.datatable','uses'=>'IssuedTicketController@datatableCancelledTicket']);

    Route::post('issued_tickets/{issued_ticket_id}/cancelled_status',  ['as'=>'issued_tickets.cancelled_status','uses'=>'IssuedTicketController@cancelled_status']);
    Route::post('issued_tickets/{issued_ticket_id}/refunded_status',  ['as'=>'issued_tickets.refunded_status','uses'=>'IssuedTicketController@refunded_status']);
    Route::post('issued_tickets/{issued_ticket_id}/reject_status',  ['as'=>'issued_tickets.reject_status','uses'=>'IssuedTicketController@reject_status']);
//   Route::get('issued_tickets/genbarcodeofticket/{id}', 'IssuedTicketController@genbarcodeofticket')->name('issued_tickets.genbarcodeofticket');
    Route::get('issued_tickets/viewissuedticket/{id}', 'IssuedTicketController@viewissuedticket')->name('issued_tickets.viewissuedticket');
    Route::get('issued_tickets/resend_ticket/{id}', 'IssuedTicketController@resend_ticket')->name('issued_tickets.resend_ticket');

app/Models/Issued_ticket.php
<?php

namespace Ticketing\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Issued_ticket extends Model
{

    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
    public static $status_YN = [1 =>'Public',2 =>'Admin'];


//    public function issued_ticket_details()
//    {
//        return $this->hasMany('Ticketing\Models\issued_ticket_detail');
//    }
    public static function boot()
    {
        parent::boot();

//        self::creating(function($object){
//            $object->event_id_str = Event::genRandomId();
//        });


        self::saving(function($object){

            if($object)
            {
                $changed = $object->isDirty() ? $object->getDirty() : false;
                $changed = empty($changed) ? false : $changed;

                if ($changed) {
                    $object->last_edit_by = Auth::user()->id;
                }
            }

        });





        Issued_ticket::deleting(function($model)
        {
            foreach ($model->issued_ticket_details as $issued_ticket_detail)
            {
                $issued_ticket_detail->delete();
            }

        });
    }


    public function issued_ticket_details()
    {
        return $this->hasMany('Ticketing\Models\Issued_ticket_detail');
    }

    public function redemption_tickets()
    {
        return $this->hasMany('Ticketing\Models\Redemption_ticket');
    }

    public function event_request_status(){
        return $this->belongsTo('Ticketing\Models\Event_request_status');
    }

    public function getIndividualTicketOfTier($issued_ticket_id,$tier_id){
           return $redemption_tickets=Redemption_ticket::where('issued_ticket_id','=',$issued_ticket_id)->where('tier_id','=',$tier_id)->get();
    }

    public function customer(){
        return $this->belongsTo('Ticketing\Models\Customer');
    }
    public static function getTierColorByTierId($id){
        $tier=Tier::find($id);
        return $tier;
    }

    // public static function getTotalAdminIssuedSum($event_request_status_id,$eventid,$ticket_from)
    // {
    //     $event_requests = Issued_ticket::where('issued_tickets.event_id','=',$eventid)->where('issued_tickets.ticket_from','=',$ticket_from)->where('event_request_status_id',$event_request_status_id)
    //         ->join('issued_ticket_details', 'issued_ticket_details.issued_ticket_id', '=', 'issued_tickets.id')
    //         ->join('tiers', 'tiers.id', '=', 'issued_ticket_details.tier_id')
    //         ->where('tiers.total_quantity_type', '=', 1)
    //         ->get();
    //     $total_qty = 0;
    //     foreach ($event_requests as $key => $event_request) {
    //         $total_qty = $total_qty + $event_request->total_qty;
    //     }
    //     return $total_qty;
    // }

    public static function getTotalAdminIssuedSum($event_request_status_id,$eventid,$ticket_from)
    {
        $event_requests = Issued_ticket::where('issued_tickets.event_id','=',$eventid)->whereIn('issued_tickets.ticket_from',[1,2])->where('event_request_status_id',$event_request_status_id)
            ->join('issued_ticket_details', 'issued_ticket_details.issued_ticket_id', '=', 'issued_tickets.id')
            ->join('tiers', 'tiers.id', '=', 'issued_ticket_details.tier_id')
            ->where('tiers.total_quantity_type', '=', 1)
            ->get();
        $total_qty = 0;
        foreach ($event_requests as $key => $event_request) {
            $total_qty = $total_qty + $event_request->total_qty;
        }
        return $total_qty;
    }

    public static function getTotalAdminIssuedSumNew($event_request_status_id,$eventid, $tier_id)
    {
        $event_requests = Issued_ticket::where('issued_tickets.event_id','=',$eventid)->where('event_request_status_id',$event_request_status_id)
            ->join('issued_ticket_details', 'issued_ticket_details.issued_ticket_id', '=', 'issued_tickets.id')
            ->where('issued_ticket_details.tier_id', $tier_id)
            ->join('tiers', 'tiers.id', '=', 'issued_ticket_details.tier_id')
            ->where('tiers.total_quantity_type', '=', 1)
            ->get();
        $total_qty = 0;
        foreach ($event_requests as $key => $event_request) {
            $total_qty = $total_qty + $event_request->total_qty;
        }
        return $total_qty;
    }

    public static function getTotalAdminIssuedFree($event_request_status_id,$eventid, $tier_id)
    {
        $event_requests = Issued_ticket::where('issued_tickets.event_id','=',$eventid)->where('event_request_status_id',$event_request_status_id)
            ->join('issued_ticket_details', 'issued_ticket_details.issued_ticket_id', '=', 'issued_tickets.id')
            ->where('issued_tickets.price_type','=',2)
            ->where('issued_tickets.ticket_from','=',2)
            ->where('issued_ticket_details.tier_id', $tier_id)
            ->join('tiers', 'tiers.id', '=', 'issued_ticket_details.tier_id')
            ->where('tiers.total_quantity_type', '=', 1)
            ->get();
        $total_qty = 0;
        foreach ($event_requests as $key => $event_request) {
            $total_qty = $total_qty + $event_request->total_qty;
        }
        return $total_qty;
    }
}

resources/views/admin/issued_tickets/_tiers_tiles.blade.php
<div class="row">
	<div class="col-md-10">
		<div class="event_listing_info" >
		    <div class="col-md-12 info-basic">
		         <span class="right-space">{{$twelve_digit_id}}</span> <span class="right-space">{{$created_at}}</span>
		    </div>
			<div class="col-md-12 info-basic">
				<span class="right-space">{{$customer_full_name}}</span>
			</div>
			<div class="col-md-12 info-basic">
				<span class="right-space">{{$customer_mobile}}</span> <span class="right-space">{{$customer_email}}</span>
			</div>

			<?php
			// echo 'pre>';
			// print_r($tiers);
             //  use App\Http\Helpers\Custom;
			?>

			@if(count($tiers)>0)
			@foreach (array_chunk($tiers,3) as $chunked_tiers)
				<div>
					@foreach ($chunked_tiers as $tier)

						{{--{{ $tier['tier_id']}}--}}
					   {{--{{'dddd'}}--}}
					{{--die;--}}

						<?php
					   $num=0;
                        $tl=$event_request->getTierColorByTierId($tier['tier_id']);



                       // $tl=\App\Http\Helpers\Custom::getTierColorByTierId($tier['tier_id']);
                       // print_r($tl);
						?>

						<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
							<div class="tier_tiles">
								<div style="margin-right:-18px;">
									<div class="col-sm-4 tile-stats-div" style="font-size: 20px; padding-top: 13px;padding-left: 4px;">
				                        <span class="tile-stats" >
				                            <span class="tile-margin-right" style="font-size: 20px;">R <strong> {{$tier['total_qty']}}</strong></span>
				                        </span>

									</div>
									<div class="col-sm-7 tile-border-left" style="background-color:#{{$tl->header_color}};color:white;">
										<center>
											<span class="tile-title" style="display: block;direction: rtl;">{{$tl->title_arabic }}</span>
										</center>
									</div>
								</div>
							</div>
						</div>
					@endforeach
					<br><br><br>
				</div>
			@endforeach
			@endif

		</div>
	</div>


</div>

resources/views/admin/issued_tickets/_viewtickets_tiers_tiles.blade.php
<div class="row">
    <div class="col-md-10 col-sm-12">
        <div class="event_listing_info">
            <div class="col-md-12 info-basic">
                @if(Route::currentRouteName() == 'issued_tickets.cancelledticket')
                    <span class="right-space"
                          style="color: black;font-size: 16px;font-weight: 700">{{$twelve_digit_id}}</span><span
                            class="right-space">{{$created_at}}</span>
                @else
                    <a style="color: black;font-size: 16px;font-weight: 700"
                       href="{{ URL::route('admin.issued_tickets.viewissuedticket',['id'=>$issued_ticket->id, 'bsource'=>$bsource]) }}"><span
                                class="right-space"
                                style="color: black;font-size: 16px;font-weight: 700">{{$twelve_digit_id}}</span></a>
                    <span class="right-space">{{$created_at}}</span>
                @endif
            </div>
            <div class="col-md-12 info-basic">
                <span class="right-space">{{$customer_full_name}}</span>
            </div>
            <div class="col-md-12 info-basic">
                <span class="right-space">{{$customer_mobile}}</span> <span
                        class="right-space">{{$customer_email}}</span>
                @if($issued_ticket->tag == 1)
                    <span class="right-space" style="color:red;font-weight: bold">VIP</span>
                @endif
            </div>

            <?php
            // echo 'pre>';
            // print_r($tiers);
            //  use App\Http\Helpers\Custom;
            ?>

            @if(count($tiers)>0)
                @foreach (array_chunk($tiers,3) as $chunked_tiers)
                    <div>
                        @foreach ($chunked_tiers as $tier)

                            {{--{{ $tier['tier_id']}}--}}
                            {{--{{'dddd'}}--}}
                            {{--die;--}}

                            <?php
                            $num = 0;
                            $tl = $issued_ticket->getTierColorByTierId($tier['tier_id']);


                            // $tl=\App\Http\Helpers\Custom::getTierColorByTierId($tier['tier_id']);
                            // print_r($tl);
                            ?>
                            @if($tl)

                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="margin-bottom: 5px">
                                    <div class="tier_tiles">
                                        <div style="margin-right:-18px;">

                                        <div class="col-sm-4 tile-stats-div"
                                             style="padding-top: 5px;padding-left: 4px;font-size: 20px">
				                                    <span class="tile-stats" style="font-size: 16px">
				                                        R <strong> {{$tier['total_qty']}}</strong>
                                                    </span>

                                        </div>
                                        <div class="col-sm-8 tile-border-left"
                                             style="background-color:#{{$tl->header_color}};color:white;height: 42px;margin-left: -18px">
                                            <center>
                                                <span class="tile-title" style="display: block;direction: rtl;">{{$tl->title_arabic }}</span>
                                            </center>
                                        </div>

                                        </div>

                                    </div>
                                </div>


                            @endif

                        @endforeach
                        <br><br><br>
                    </div>
                @endforeach
            @endif

        </div>
    </div>


</div>

resources/views/admin/issued_tickets/create22.blade.php
@include('admin.events.form',['event'=>$event,'tags'=>$tags,'request_type'=>$request_type])